### ISSUE TITLE
Segfault in GCC 7.1.1 Fedora 26

### ISSUE THREAD

**Issue by rickyzhang82** [cebix/macemu#117]
Machine
```Bash
Kernel 4.11.11-300.fc26.x86_64
GCC 7.1.1
```
Configure
```Bash
make clean
NO_CONFIGURE=1 ./autogen.sh
./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk
make -j 32
```
~/.sheepshaver_prefs 
```Bash
disk /home/Ricky/repo/PPC.Mac.Emulator/SheepShaver/DiskImage/OS9.img
disk /home/Ricky/repo/PPC.Mac.Emulator/SheepShaver/DiskImage/DiskImg.img
extfs /
screen win/640/480
windowmodes 0
screenmodes 0
seriala /dev/ttyS0
serialb /dev/ttyS1
rom /home/Ricky/repo/PPC.Mac.Emulator/SheepShaver/ROM/1997-11 - 79D68D63 - Power Mac G3 desktop.ROM
bootdrive 0
bootdriver 0
ramsize 1073741824
frameskip 8
gfxaccel true
nocdrom true
nonet false
nosound false
nogui false
noclipconversion false
ignoresegv true
ignoreillegal false
jit false
jit68k false
keyboardtype 5
keycodes false
mousewheelmode 1
mousewheellines 3
dsp /dev/dsp
mixer /dev/mixer
ignoresegv true
idlewait true
```

I can get SheepShavere compiled. But when I start image, I got a segfault even I set ignoresegv as true.

Output
```Bash
./SheepShaver 
SheepShaver V2.4 by Christian Bauer and Mar"c" Hellwig
Reading ROM file...
Using SDL/pulse audio output
Detected CPU features: MMX SSE SSE2 SSE3 SSSE3
PowerPC CPU emulator by Gwenole Beauchesne
WARNING: Unknown DiskStatus(6)
Segmentation fault (core dumped)
```

I wonder if GCC 7.1.1 or new kernel cause the trouble. Since I disable JIT, I need to dig deeper in the core dump.

**Comment by rickyzhang82** [comment]
Coredump
```Bash
           PID: 15625 (SheepShaver)
           UID: 500 (Ricky)
           GID: 500 (Ricky)
        Signal: 11 (SEGV)
     Timestamp: Thu 2017-08-10 20:17:25 EDT (4min 58s ago)
  Command Line: ./SheepShaver
    Executable: /home/Ricky/repo/github/macemu/SheepShaver/src/Unix/SheepShaver
 Control Group: /user.slice/user-500.slice/user@500.service/gnome-terminal-server.service
          Unit: user@500.service
     User Unit: gnome-terminal-server.service
         Slice: user-500.slice
     Owner UID: 500 (Ricky)
       Boot ID: d0fdf2319aa442d4a55fb830a4606f96
    Machine ID: c5239f8b74e38b899f863b4c0000000a
      Hostname: gtx
       Storage: /var/lib/systemd/coredump/core.SheepShaver.500.d0fdf2319aa442d4a55fb830a4606f96.15625.1502410645000000.lz4
       Message: Process 15625 (SheepShaver) of user 500 dumped core.
                
                Stack trace of thread 15625:
                #0  0x00000000780a5461 vm_do_write_memory_4 (SheepShaver)
                #1  0x000000007809b40a _ZNK13nv_mem_fun1_tIv11powerpc_cpujEclEPS0_j (SheepShaver)
                #2  0x0000000078050c7f _Z11jump_to_romj (SheepShaver)
                #3  0x00007f266778c4da __libc_start_main (libc.so.6)
                #4  0x000000007804f0fa _start (SheepShaver)
                
                Stack trace of thread 15643:
                #0  0x00007f266788bdb5 __clock_nanosleep (libc.so.6)
                #1  0x000000007805b466 timer_func (SheepShaver)
                #2  0x00007f266abb136d start_thread (libpthread.so.0)
                #3  0x00007f266787cb8f __clone (libc.so.6)
                
                Stack trace of thread 15629:
                #0  0x00007f2667877529 syscall (libc.so.6)
                #1  0x00007f26689756fa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007f2668904b31 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)
                #3  0x00007f26689050ec g_async_queue_timeout_pop (libglib-2.0.so.0)
                #4  0x00007f2668957fde g_thread_pool_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f2668957536 g_thread_proxy (libglib-2.0.so.0)
                #6  0x00007f266abb136d start_thread (libpthread.so.0)
                #7  0x00007f266787cb8f __clone (libc.so.6)
                
                Stack trace of thread 15645:
                #0  0x00007f2667872cd3 __select (libc.so.6)
                #1  0x000000007805c03b _Z10Delay_usecj (SheepShaver)
                #2  0x000000007804f978 tick_func (SheepShaver)
                #3  0x00007f266abb136d start_thread (libpthread.so.0)
                #4  0x00007f266787cb8f __clone (libc.so.6)
                
                Stack trace of thread 15642:
                #0  0x00007f2667870b76 ppoll (libc.so.6)
                #1  0x00007f2659a845b1 pa_mainloop_poll (libpulse.so.0)
                #2  0x00007f2659a84bc0 pa_mainloop_iterate (libpulse.so.0)
                #3  0x00007f266a94238d PULSE_WaitAudio (libSDL-1.2.so.0)
                #4  0x00007f266a91611c SDL_RunAudio (libSDL-1.2.so.0)
                #5  0x00007f266a91e7b8 SDL_RunThread (libSDL-1.2.so.0)
                #6  0x00007f266a960db9 RunThread (libSDL-1.2.so.0)
                #7  0x00007f266abb136d start_thread (libpthread.so.0)
                #8  0x00007f266787cb8f __clone (libc.so.6)
                
                Stack trace of thread 15627:
                #0  0x00007f2667870a9d poll (libc.so.6)
                #1  0x00007f2668930569 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                #2  0x00007f266893067c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f26689306c1 glib_worker_main (libglib-2.0.so.0)
                #4  0x00007f2668957536 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f266abb136d start_thread (libpthread.so.0)
                #6  0x00007f266787cb8f __clone (libc.so.6)
                
                Stack trace of thread 15644:
                #0  0x00007f2667872cd3 __select (libc.so.6)
                #1  0x000000007805c03b _Z10Delay_usecj (SheepShaver)
                #2  0x0000000078076f7d redraw_func (SheepShaver)
                #3  0x00007f266a91e7b8 SDL_RunThread (libSDL-1.2.so.0)
                #4  0x00007f266a960db9 RunThread (libSDL-1.2.so.0)
                #5  0x00007f266abb136d start_thread (libpthread.so.0)
                #6  0x00007f266787cb8f __clone (libc.so.6)
                
                Stack trace of thread 15646:
                #0  0x00007f2667872cd3 __select (libc.so.6)
                #1  0x000000007805c03b _Z10Delay_usecj (SheepShaver)
                #2  0x000000007804f87a nvram_func (SheepShaver)
                #3  0x00007f266abb136d start_thread (libpthread.so.0)
                #4  0x00007f266787cb8f __clone (libc.so.6)
                
                Stack trace of thread 15628:
                #0  0x00007f2667870a9d poll (libc.so.6)
                #1  0x00007f2668930569 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                #2  0x00007f2668930902 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f2669375cb6 gdbus_shared_thread_func (libgio-2.0.so.0)
                #4  0x00007f2668957536 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f266abb136d start_thread (libpthread.so.0)
                #6  0x00007f266787cb8f __clone (libc.so.6)

GNU gdb (GDB) Fedora 8.0-13.fc26
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/Ricky/repo/github/macemu/SheepShaver/src/Unix/SheepShaver...done.
[New LWP 15625]
[New LWP 15643]
[New LWP 15629]
[New LWP 15645]
[New LWP 15642]
[New LWP 15627]
[New LWP 15644]
[New LWP 15646]
[New LWP 15628]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./SheepShaver'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  vm_do_write_memory_4 (v=<optimized out>, a=<optimized out>) at ../kpx_cpu/src/cpu/vm.hpp:69
69	static inline void vm_do_write_memory_4(uint32 *a, uint32 v) { *a = bswap_32(v); }
[Current thread is 1 (Thread 0x7f266af80200 (LWP 15625))]
```

**Comment by rickyzhang82** [comment]
Stack
```bash
(gdb) bt
#0  0x00000000780a5461 in vm_do_write_memory_4 (v=<optimized out>, a=<optimized out>) at ../kpx_cpu/src/cpu/vm.hpp:69
#1  0x00000000780a5461 in vm_write_memory_4 (value=<optimized out>, addr=1084227120) at ../kpx_cpu/src/cpu/vm.hpp:258
#2  0x00000000780a5461 in memory_helper<4, false>::store(unsigned int, unsigned int) (value=<optimized out>, ea=1084227120) at ../kpx_cpu/src/cpu/ppc/ppc-execute.cpp:563
#3  0x00000000780a5461 in powerpc_cpu::execute_loadstore<op_template_nop<unsigned int>, input_gpr_except<bit_field<11, 15>, 0>, immediate_operand<bit_field<16, 31>, op_sign_extend_16_32>, false, 4, false, false>(unsigned int) (this=0x791e5490, opcode=<optimized out>) at ../kpx_cpu/src/cpu/ppc/ppc-execute.cpp:575
#4  0x000000007809b40a in nv_mem_fun1_t<void, powerpc_cpu, unsigned int>::operator()(powerpc_cpu*, unsigned int) const (x=<optimized out>, p=0x791e5490, this=0x4030f730) at ../kpx_cpu/include/nvmemfun.hpp:88
#5  0x000000007809b40a in powerpc_cpu::execute(unsigned int) (this=0x791e5490, entry=entry@entry=1085341696) at ../kpx_cpu/src/cpu/ppc/ppc-cpu.cpp:684
#6  0x00000000780b04de in emul_ppc(unsigned int) (entry=entry@entry=1085341696) at ../kpx_cpu/sheepshaver_glue.cpp:927
#7  0x0000000078050c7f in jump_to_rom(unsigned int) (entry=1085341696) at main_unix.cpp:1205
#8  0x0000000078050c7f in emul_func (arg=0x0) at main_unix.cpp:1225
#9  0x0000000078050c7f in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at main_unix.cpp:1046

```

**Comment by monreal** [comment]
Same here with the official package (SheepShaver-2.4-0.3.20160322.fc26.x86_64) on Fedora 26.

**Comment by rickyzhang82** [comment]
I don't think Fedora distribute SheepShaver package. It must be from unofficial RPM fusions channel.

**Comment by monreal** [comment]
You are totally right @rickyzhang82 the package I installed came from rpmfusion-free.
